name: Install, test, and segment
on:
  workflow_call:
    inputs:
      algo_list:
        required: true
        type: string
      runner:
        required: true
        type: string
jobs:
  analysis:
    name: Analysis

    if: ${{ inputs.algo_list != '[]' }}
    runs-on: ${{ fromJSON(inputs.runner) }}

    # Default shell for ALL subsequent steps.
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@master

    - uses: actions/download-artifact@v4
      with:
        path: /home/runner/work/seg_ci/seg_ci/data/

    - uses: actions/checkout@master
    - name: Unzip artifacts
      run: |
      ls /home/runner/work/seg_ci/seg_ci/data/

    - name: Install ADS
      run: |
      git clone https://www.github.com/axondeepseg/axondeepseg.git
      cd axondeepseg
      ./install_ads -y

      source ads_conda/bin/activate ads_conda/envs/venv_ads

