name: Install, test, and segment
on:
  workflow_call:
    inputs:
      algo_list:
        required: true
        type: string
      runner:
        required: true
        type: string
jobs:
  analysis:
    name: Analysis
    
    runs-on: ubuntu-latest

    # Default shell for ALL subsequent steps.
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@master

    - uses: actions/download-artifact@v4
      with:
        path: /home/runner/work/seg_ci/seg_ci/data/

    - name: Unzip artifacts
      run: |
          pwd
          cur_dir=$(pwd)
          data_dir=/home/runner/work/seg_ci/seg_ci/data
          cd $data_dir
          ls
          for filename in *.tar.gz; do
            cd $filename
            tar -xvf $filename
            cd ..
          done
          pwd
          cd $cur_dir
          pwd

    - name: Install ADS
      run: |
          pwd
          git clone https://www.github.com/axondeepseg/axondeepseg.git
          cd axondeepseg
          ./install_ads -y

          source ads_conda/bin/activate ads_conda/envs/venv_ads
          cd ..
          pwd

    - name: Run morphometrics
      run: |
          echo $data_dir
          cd /home/runner/work/seg_ci/seg_ci/data
          ls
          source activate /home/runner/work/seg_ci/seg_ci/axondeepseg/ads_conda/envs/venv_ads
          for filename in *.tar.gz; do
            ls
            cd $filename
            cd data
            
            cd sem
            axondeepseg_morphometrics -i image_seg-axonmyelin.png -f axon_morphometrics.csv
            cd ..
            
            cd tem
            axondeepseg_morphometrics -i image_seg-axonmyelin.png -f axon_morphometrics.csv
            cd ..

            cd ..
            cd ..
          done
