name: Install, test, and segment
on:
  workflow_call:
    inputs:
      algo_list:
        required: true
        type: string
      runner:
        required: true
        type: string
jobs:
  analysis:
    name: Analysis
    
    runs-on: ubuntu-latest

    # Default shell for ALL subsequent steps.
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@master

    - uses: actions/download-artifact@v4
      with:
        path: /home/runner/work/seg_ci/seg_ci/data/

    - name: Unzip artifacts
      run: |
          cur_dir=pwd
          cd /home/runner/work/seg_ci/seg_ci/data
          ls
          for filename in *.tar.gz; do
            ls
            cd $filename
            ls
            tar -xvf $filename
            ls
            cd data
            ls
            cd sem
            ls
            cd ..
            cd ..
            cd ..

          done
          ls
          cd $cur_dir

    - name: Install ADS
      run: |
          git clone https://www.github.com/axondeepseg/axondeepseg.git
          cd axondeepseg
          ./install_ads -y

          source ads_conda/bin/activate ads_conda/envs/venv_ads

