name: Reconstruct and evaluate
on:
  workflow_call:
    inputs:
      algo_list:
        required: true
        type: string
      runner:
        required: true
        type: string
jobs:
  # Defining matrix for OS and Python
  recon_and_evaluate:
    name: Matrix Test

    if: ${{ inputs.algo_list != '[]' }}
    runs-on: ${{ fromJSON(inputs.runner) }}

    # Default shell for ALL subsequent steps.
    defaults:
      run:
        shell: bash -l {0}

    # Defining matrix for OS and Python
    strategy:
      fail-fast: false
      matrix:
        algo: ${{ fromJSON(inputs.algo_list) }}

    steps:
    - uses: actions/checkout@v3
    - name: Get modified algorithms
      id: getfile
      run: |
        
      shell: bash

    # Step 2: Install environment.
    - name: Install Conda Env All OS
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.9
        activate-environment: venv
        auto-update-conda: true
        environment-file: environment.yml

    # Step 3: List conda info, conda packages
    - name: Conda info and list
      # List
      run: |
        conda info
        conda list
    
    - name: Reconstruct and evaluate
      run: |
        #sudo apt-get update
        #sudo apt-get install python3.10 python3.10-venv python-is-python3 -y
        #pip install osfclient argparse numpy scikit-learn scikit-image scipy
        export PATH=$PATH:/home/runnerx/.local/bin

        export PIPELINE_NAME="$(basename "${{ matrix.algo }}")"
        
        bash run.sh algos/${PIPELINE_NAME}

        ls

        ls output
        ls output/${PIPELINE_NAME}/

        cd output
        pwd

        cd ${PIPELINE_NAME}/
        pwd

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Segmentation files
        path: |
          /home/runner/work/seg_ci/seg_ci/output/${PIPELINE_NAME}/output.tar.gz